# Generated by Django 6.0.2 on 2026-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('company_name', models.CharField(max_length=500)),
                ('company_id', models.CharField(blank=True, max_length=50)),
                ('company_url', models.URLField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('contract_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer')], max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('Entry level', 'Entry level'), ('Mid-Senior level', 'Mid-Senior level'), ('Associate', 'Associate'), ('Director', 'Director'), ('Executive', 'Executive'), ('Internship', 'Internship')], max_length=50)),
                ('work_type', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=500)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('benefits', models.TextField(blank=True)),
                ('job_url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('apply_type', models.CharField(blank=True, choices=[('EASY_APPLY', 'Easy Apply'), ('EXTERNAL', 'External')], max_length=20)),
                ('applications_count', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('posted_time', models.CharField(blank=True, max_length=100)),
                ('poster_profile_url', models.URLField(blank=True, max_length=1000)),
                ('poster_full_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='job_search__company_cf5e0b_idx'), models.Index(fields=['location'], name='job_search__locatio_a4cadb_idx'), models.Index(fields=['experience_level'], name='job_search__experie_6551f8_idx'), models.Index(fields=['published_at'], name='job_search__publish_f2d5ee_idx')],
            },
        ),
    ]
