# Generated by Django 5.2.11 on 2026-02-10 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTaskJob',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeTierLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_normalized', models.CharField(max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2'), ('TIER_3', 'Tier 3')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
                ('source_model', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['tier'], name='job_search__tier_c5eea0_idx'), models.Index(fields=['last_verified_at'], name='job_search__last_ve_ca9622_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateRankingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_candidates', models.PositiveIntegerField(default=0)),
                ('processed_candidates', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('batch_size', models.PositiveIntegerField(default=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('timing_metrics', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_runs', to='job_search.companytaskjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('company_name', models.CharField(max_length=500)),
                ('company_id', models.CharField(blank=True, max_length=50)),
                ('company_url', models.URLField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('contract_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer')], max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('Entry level', 'Entry level'), ('Mid-Senior level', 'Mid-Senior level'), ('Associate', 'Associate'), ('Director', 'Director'), ('Executive', 'Executive'), ('Internship', 'Internship')], max_length=50)),
                ('work_type', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=500)),
                ('work_mode', models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], db_index=True, max_length=20, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], db_index=True, max_length=20, null=True)),
                ('internship_duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('SME', 'SME'), ('STARTUP', 'Startup'), ('MNC', 'MNC')], db_index=True, max_length=20, null=True)),
                ('stipend_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('benefits', models.TextField(blank=True)),
                ('job_url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('apply_type', models.CharField(blank=True, choices=[('EASY_APPLY', 'Easy Apply'), ('EXTERNAL', 'External')], max_length=20)),
                ('applications_count', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('posted_time', models.CharField(blank=True, max_length=100)),
                ('poster_profile_url', models.URLField(blank=True, max_length=1000)),
                ('poster_full_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='job_search__company_cf5e0b_idx'), models.Index(fields=['location'], name='job_search__locatio_a4cadb_idx'), models.Index(fields=['experience_level'], name='job_search__experie_6551f8_idx'), models.Index(fields=['published_at'], name='job_search__publish_f2d5ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('resume_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_candidates', to='job_search.companytaskjob')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('passes_hard_filter', models.BooleanField(default=False)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sub_scores', models.JSONField(blank=True, default=dict)),
                ('filter_reasons', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='job_search.candidaterankingrun')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to='job_search.jobcandidate')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='AgentTraceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_events', to='job_search.candidaterankingrun')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_events', to='job_search.jobcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], max_length=20)),
                ('internship_duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('company_size_preference', models.CharField(choices=[('SME', 'SME'), ('STARTUP', 'Startup'), ('MNC', 'MNC')], max_length=20)),
                ('stipend_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILTERING', 'Filtering'), ('AGENT_RUNNING', 'Agent Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('preferences_snapshot', models.JSONField()),
                ('candidate_profile_snapshot', models.JSONField(blank=True, null=True)),
                ('filtered_jobs_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('timing_metrics', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('selection_probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fit_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('job_quality_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('why', models.TextField()),
                ('agent_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='job_search.job')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='job_search.matchingrun')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterJobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_tiers', models.JSONField(default=list)),
                ('min_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('max_experience_years', models.DecimalField(decimal_places=1, default=2, max_digits=4)),
                ('coding_platform_criteria', models.JSONField(default=list)),
                ('number_of_openings', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_preference', to='job_search.companytaskjob')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume_data', models.JSONField()),
                ('gpt_score', models.IntegerField(blank=True, null=True)),
                ('gpt_verdict', models.CharField(blank=True, max_length=100, null=True)),
                ('gpt_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='job_search.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='candidaterankingrun',
            index=models.Index(fields=['job', '-created_at'], name='job_search__job_id_68e23b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterankingrun',
            index=models.Index(fields=['status'], name='job_search__status_82b968_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcandidate',
            index=models.Index(fields=['email'], name='job_search__email_15c2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcandidate',
            index=models.Index(fields=['job', 'created_at'], name='job_search__job_id_eb0f84_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcandidate',
            constraint=models.UniqueConstraint(fields=('job', 'email'), name='unique_candidate_email_per_company_task_job'),
        ),
        migrations.AddConstraint(
            model_name='candidaterankingresult',
            constraint=models.UniqueConstraint(fields=('run', 'rank'), name='unique_candidate_rank_per_run'),
        ),
        migrations.AddConstraint(
            model_name='candidaterankingresult',
            constraint=models.UniqueConstraint(fields=('run', 'candidate'), name='unique_candidate_result_per_run'),
        ),
        migrations.AddIndex(
            model_name='agenttraceevent',
            index=models.Index(fields=['run', 'stage'], name='job_search__run_id_7d127e_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttraceevent',
            index=models.Index(fields=['candidate', 'stage'], name='job_search__candida_8c7a99_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_job_pref_per_user'),
        ),
        migrations.AddConstraint(
            model_name='jobpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stipend_max__isnull', True), ('stipend_min__isnull', True)), ('stipend_min__lte', models.F('stipend_max')), _connector='OR'), name='job_pref_stipend_min_lte_max'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['user', '-created_at'], name='job_search__user_id_a31c61_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['status'], name='job_search__status_4ae7e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingresult',
            constraint=models.UniqueConstraint(fields=('run', 'rank'), name='unique_rank_per_run'),
        ),
        migrations.AddConstraint(
            model_name='matchingresult',
            constraint=models.UniqueConstraint(fields=('run', 'job'), name='unique_job_per_run'),
        ),
        migrations.AddIndex(
            model_name='recruiterjobpreference',
            index=models.Index(fields=['updated_at'], name='job_search__updated_24fc8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruiterjobpreference',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_openings__gte', 1)), name='recruiter_pref_openings_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='recruiterjobpreference',
            constraint=models.CheckConstraint(condition=models.Q(('min_experience_years__lte', models.F('max_experience_years'))), name='recruiter_pref_min_exp_lte_max_exp'),
        ),
    ]
