# Generated by Django 5.2.11 on 2026-02-07 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_alter_job_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, choices=[('SME', 'SME'), ('STARTUP', 'Startup'), ('MNC', 'MNC')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='internship_duration_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stipend_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stipend_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stipend_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], max_length=20)),
                ('internship_duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('company_size_preference', models.CharField(choices=[('SME', 'SME'), ('STARTUP', 'Startup'), ('MNC', 'MNC')], max_length=20)),
                ('stipend_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stipend_min__isnull', True), ('stipend_max__isnull', True), ('stipend_min__lte', models.F('stipend_max')), _connector='OR'), name='job_pref_stipend_min_lte_max'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_job_pref_per_user')],
            },
        ),
    ]
