# Generated by Django 5.2.11 on 2026-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_job_company_size_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('SME', 'SME'), ('MSME', 'MSME'), ('STARTUP', 'Startup'), ('MNC', 'MNC'), ('ENTERPRISE', 'Enterprise'), ('GOVERNMENT', 'Government')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('FREELANCE', 'Freelance')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobpreference',
            name='company_size_preference',
            field=models.CharField(choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('SME', 'SME'), ('MSME', 'MSME'), ('STARTUP', 'Startup'), ('MNC', 'MNC'), ('ENTERPRISE', 'Enterprise'), ('GOVERNMENT', 'Government')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpreference',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('FREELANCE', 'Freelance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpreference',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite')], max_length=20),
        ),
    ]
