# Generated by Django 5.2.11 on 2026-02-07 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0005_alter_job_company_size_alter_job_employment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, choices=[('SME', 'SME'), ('STARTUP', 'Startup'), ('MNC', 'MNC')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobpreference',
            name='company_size_preference',
            field=models.CharField(choices=[('SME', 'SME'), ('STARTUP', 'Startup'), ('MNC', 'MNC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpreference',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpreference',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], max_length=20),
        ),
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILTERING', 'Filtering'), ('AGENT_RUNNING', 'Agent Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('preferences_snapshot', models.JSONField()),
                ('candidate_profile_snapshot', models.JSONField(blank=True, null=True)),
                ('filtered_jobs_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('timing_metrics', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('selection_probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fit_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('job_quality_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('why', models.TextField()),
                ('agent_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='job_search.job')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='job_search.matchingrun')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['user', '-created_at'], name='job_search__user_id_a31c61_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingrun',
            index=models.Index(fields=['status'], name='job_search__status_4ae7e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingresult',
            constraint=models.UniqueConstraint(fields=('run', 'rank'), name='unique_rank_per_run'),
        ),
        migrations.AddConstraint(
            model_name='matchingresult',
            constraint=models.UniqueConstraint(fields=('run', 'job'), name='unique_job_per_run'),
        ),
    ]
