# Generated by Django 5.2.11 on 2026-02-10 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0006_alter_job_company_size_alter_job_employment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume_data', models.JSONField()),
                ('gpt_score', models.IntegerField(blank=True, null=True)),
                ('gpt_verdict', models.CharField(blank=True, max_length=100, null=True)),
                ('gpt_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='jobpreference',
            name='job_pref_stipend_min_lte_max',
        ),
        migrations.AddConstraint(
            model_name='jobpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stipend_max__isnull', True), ('stipend_min__isnull', True)), ('stipend_min__lte', models.F('stipend_max')), _connector='OR'), name='job_pref_stipend_min_lte_max'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='job_search.task'),
        ),
    ]
