# Generated by Django 5.2.11 on 2026-02-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0007_candidate_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(blank=True, max_length=100)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('preference_name', models.CharField(blank=True, max_length=100)),
                ('snapshot_before', models.JSONField(blank=True, default=dict)),
                ('snapshot_after', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='jobpreference',
            name='unique_active_job_pref_per_user',
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='excluded_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='excluded_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='excluded_sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Entry level', 'Entry level'), ('Mid-Senior level', 'Mid-Senior level'), ('Associate', 'Associate'), ('Director', 'Director'), ('Executive', 'Executive'), ('Internship', 'Internship')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='preferred_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='preferred_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='preferred_sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='jobpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_active_pref_name_per_user'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='job_search.job'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='job_search.jobpreference'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferencechangelog',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='job_search.jobpreference'),
        ),
        migrations.AddField(
            model_name='preferencechangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['user', '-created_at'], name='job_search__user_id_23c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['is_read'], name='job_search__is_read_1e37ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobalert',
            constraint=models.UniqueConstraint(fields=('user', 'preference', 'job'), name='unique_alert_per_user_pref_job'),
        ),
        migrations.AddIndex(
            model_name='preferencechangelog',
            index=models.Index(fields=['user', '-created_at'], name='job_search__user_id_529187_idx'),
        ),
    ]
